### ISSUE TITLE
Google - Dark theme with TV is not visible

### ISSUE THREAD

**Issue by ZoltanSzilagyiCse** [liri/lovelace-themes#7]
**Is your feature request related to a problem? Please describe.**
Switching from default theme to Google - Dark the icon of the TV appears white

**Describe the solution you'd like**
A dark image (like a material one as in the default theme)

**Describe alternatives you've considered**
Or we can remove the image and just display a 0x0px element without height/width

**Additional context**
See the attached screenshot
![image](https://user-images.githubusercontent.com/14167557/73600059-93a2b880-454b-11ea-9717-d668987be70e.png)
![image](https://user-images.githubusercontent.com/14167557/73600068-afa65a00-454b-11ea-95ae-46adb19ae176.png)
And here is the config for the card (it's just a basic media player)
```
entity: media_player.tv
type: media-control
```

**Comment by stavlocker** [comment]
+1, for me this just makes the entire media player disappear:
![image](https://user-images.githubusercontent.com/30472563/93661556-53079900-fa61-11ea-8645-f4986c9b36b8.png)
But the buttons are still there. It appears that the .background element is blocking everything from being viewed, because it's background color is the "primary-color" variable which is set to the same color as the text (white in dark mode, black in light mode)

**Comment by Zelaf** [comment]
This is an issue for me too. A fix would be appreciated!

![image](https://user-images.githubusercontent.com/10819462/178422500-68f7760a-5e8e-47ab-8481-8a9801bbb502.png)
![image](https://user-images.githubusercontent.com/10819462/178422606-e044c9de-ae97-485d-b399-df2b1396a8bf.png)

**Comment by liri** [comment]
honestly i'm surprised this theme is still in use except by me :)
please check the potential fix on the branch created for this issue:
https://github.com/liri/lovelace-themes/blob/7-google-dark-theme-with-tv-is-not-visible/themes/google-home.yaml
